name: "daigoroubot"
author: "gam0022"
admin: 
  - "gam0022"
  - "gam00222"

files:
  db:  "general.db"
  cer: "ca.cer"

oauth:
  ConsumerKey:
  ConsumerSecret:
  OauthToken:
  OauthTokenSecret:

ReplayTable:
  all:
    - 
      - ["おはよう", !ruby/regexp /^(お|起)きた/, "むくり", "起床", "ムクリ", "ﾑｸﾘ", "おはよ", "okita"]
      - ["おはようなのだ！", "やっと起きたのかなのだ", "早くしないと、遅刻するのだ"]
    - 
      - ["だいごろう", "大五郎", "だいごろー", "daigorou"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["落ち込んでる", "欝だ", "低まる", "絶望した"]
      - ["どうしたのだ？", "元気を出すのだ！", "大丈夫かなのだ？"]
    - 
      - ["こんにちは", "こんにちわ", "hello", "はろー"]
      - ["こんにちわなのだ", "わんわん！", "はろーー", "(/ω・＼)ﾁﾗｯ"]
    - 
      - ["おやすみ","ねるか", "寝る", "ｵﾔｽﾐ"]
      - ["おやすみなのだ！", "さっさと寝るのだw", "おやすみ、また明日なのだ！", "また明日なのだ！"]
    - 
      - ["こんばんわ", "こんばんは"]
      - ["こんばんわなのだ！", "こんばんはなのだ！！"]
    - 
      - ["出発", "でっぱつ", "いってきます"]
      - ["いってらなのだ!"]
    - 
      - ["帰宅", "ただいま", "帰った"]
      - ["おかえりなのだ！", "おつかれなのだ！", "おかえりなのだ。"]
#    - 
#      - ["うける", "ウケる", "ウケル"]
#      - ["うけるーなのだ"]
#    - 
#      - ["死にたい"]
#      - ["僕は平成15年の夏に死んだのだ…。", "死んだら遺灰はのこるのか? なのだ"]
#    - 
#      - ["バレンタイン", "チョコ", "ちょこ", "バレンタイン"]
#      - ["僕もチョコが欲しいのだ！", "チョコ食べたいのだ！", "チョコ貰えるといいね！なのだ！"]
#    - 
#      - ["寒い", "さむい"]
#      - ["つくばの冬は僕の故郷のアラスカ並に寒いのだ…", "僕の冬毛をもってしても、つくばは寒いのだ…"]
#    - 
#      - ["バイト"]
#      - ["お疲れなのだ！", "バイト乙なのだ！", "おつかれーなのだ！"]

  mention:
    - 
      - ["ありがと"]
      - ["どういたしましてーなのだ！", "どーもなのだ。", "どういたしましてなのだ。"]
    - 
      - ["もふ", "もっふ"]
      - ["そんなに僕の毛皮でもふもふしたい？なのだ！", "僕の毛皮はもふもふなのだ！", "触ってみる？なのだ！"]
    - 
      - ["もしもし"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["わんわん"]
      - ["（Ｕ＾ω＾）<わんわんお！", "わんわんわん！！", "<わんわん!!"]
    - 
      - ["だまれ", "うざい", "寝ない", "ねない", "違う", "ちがう"]
      - ["ごめんなのだ…", "(；Uﾟωﾟ)<すまないのだ！"]
 

WordsOnFaildRegularTweet: 
  - "（Ｕ＾ω＾）わんわんお！なのだ"
  - "はあ、眠いのだ（Ｕ-ω-）zzz"
  - "僕の毛皮はふかふかなのだ"
  - "僕はアラスカンマラミュートという犬種なのだ"
  - "僕はまだ3歳なのだ"
  - "大五郎botって既出だったのかーなのだ…"
WordsOnFaildReply:
  - "そーなのだ"
  - "今は眠いのだ"
  - "そうなのだ（Ｕ＾ω＾）"
  - "呼ばれたかなのだ？"
  - "僕のことを呼んだかなのだ？"
  - "｜ω･`）チラッ"
  - "｜･ω･`） ソー…"

Users:
  follow:
    - 92410518
    - 324380957
    - 246793872
    - 117341077
    - 135175693
    - 123862630
    - 128909217
    - 50046492 
    - 206248292
    - 86049415 
    - 14919778 
    - 282303420
    - 60046536 
    - 94797531 
    - 319554874
    - 84843705 
    - 90394630 
    - 427475071
    - 281079401
  remove:
    - "yamatosi3134"
    - "ameburo1"
    - "MARS_ON_Spotify"
    - "ios_dev_news"
    - "PhilnRaleigh"
    - "virtualworks1"
    - "WorldWide1001"
    - "kayo_silva15"
    - "TiagoJanatico"
    - "rnt_vdr"
    - "EsparZa_ROck"
    - "andre_estiano"
    - "Reglerium"
    - "licosupremus"
    - "pillowjack"
  ignore:
    - "run_entry"
