name: "daigoroubot"
author: "gam0022"
admin: 
  - "gam0022"
  - "gam00222"

files:
  db:  "general.db"
  cer: "ca.cer"

oauth:
  ConsumerKey:     
  ConsumerSecret:  
  OauthToken:      
  OauthTokenSecret:

ReplayTable:
  all:
    - 
      - ["おはよう", !ruby/regexp /^おきた/, "むくり", "起床", "起きた", "ムクリ", "ﾑｸﾘ", "おはよ", "okita"]
      - ["おはようなのだ！", "やっと起きたのかなのだ", "早くしないと、遅刻するのだ"]
    - 
      - ["だいごろう", "大五郎", "だいごろー"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["落ち込んでる", "欝だ", "低まる", "絶望した"]
      - ["どうしたのだ？", "元気を出すのだ！", "大丈夫かなのだ？"]
    - 
      - ["こんにちは", "こんにちわ", "hello", "はろー"]
      - ["こんにちわなのだ", "わんわん！", "はろーー", "(/ω・＼)ﾁﾗｯ"]
    - 
      - ["おやすみ","ねるか", "寝る", "ｵﾔｽﾐ"]
      - ["おやすみなのだ！", "さっさと寝るのだw", "おやすみ、また明日なのだ！", "また明日なのだ！"]
    - 
      - ["こんばんわ", "こんばんは"]
      - ["こんばんわなのだ！", "こんばんはなのだ！！"]
    - 
      - ["出発", "でっぱつ", "いってきます"]
      - ["いってらなのだ!"]
    - 
      - ["帰宅", "ただいま", "帰った"]
      - ["おかえりなのだ！", "おつかれなのだ！", "おかえりなのだ。"]
#    - 
#      - ["バレンタイン", "チョコ", "ちょこ", "バレンタイン"]
#      - ["僕もチョコが欲しいのだ！", "チョコ食べたいのだ！", "チョコ貰えるといいね！なのだ！"]
#    - 
#      - ["寒い", "さむい"]
#      - ["つくばの冬は僕の故郷のアラスカ並に寒いのだ…", "僕の冬毛をもってしても、つくばは寒いのだ…"]
    - 
      - ["バイト"]
      - ["お疲れなのだ！", "バイト乙なのだ！", "おつかれーなのだ！"]

  mention:
    - 
      - ["ありがと"]
      - ["どういたしましてーなのだ！", "どーもなのだ。", "どういたしましてなのだ。"]
    - 
      - ["もふ", "もっふ"]
      - ["そんなに僕の毛皮でもふもふしたい？なのだ！", "僕の毛皮はもふもふなのだ！", "触ってみる？なのだ！"]
    - 
      - ["もしもし"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["わんわん"]
      - ["（Ｕ＾ω＾）<わんわんお！", "わんわんわん！！", "<わんわん!!"]
    - 
      - ["だまれ", "うざい", "寝ないよ", "ちがう", "ねない"]
      - ["ごめんなのだ…", "(；Uﾟωﾟ)<すまないのだ！"]
 

WordsOnFaildRegularTweet: 
  - "（Ｕ＾ω＾）わんわんお！なのだ"
  - "はあ、眠いのだ（Ｕ-ω-）zzz"
  - "僕の毛皮はふかふかなのだ"
  - "僕はアラスカンマラミュートという犬種なのだ"
  - "僕はまだ3歳なのだ"
  - "大五郎botって既出だったのかーなのだ…"
WordsOnFaildReply:
  - "そーなのだ"
  - "今は眠いのだ"
  - "そうなのだ（Ｕ＾ω＾）"
  - "呼ばれたかなのだ？"
  - "僕のことを呼んだかなのだ？"
  - "｜ω･`）チラッ"
  - "｜･ω･`） ソー…"

kataomoi_ids:
  - 92410518
  - 324380957
  - 246793872
  - 117341077
  - 135175693
  - 123862630
  - 128909217
  - 50046492 
  - 206248292
  - 86049415 
  - 14919778 
  - 282303420
  - 60046536 
  - 94797531 
  - 319554874
  - 84843705 
  - 90394630 
  - 427475071
  - 205090650
  - 281079401
  - 96223948 
  - 202998073
  - 256401886
  - 224163555
  - 95892026 
  - 113427374
  - 2632291  
  - 9334242  
  - 42816371 
  - 204245399
