name: "daigoroubot"
author: "gam0022"
admin: 
  - "gam0022"
  - "gam00222"

files:
  db:  "general.db"
  cer: "ca.cer"

oauth:
  ConsumerKey:       
  ConsumerSecret:    
  OauthToken:        
  OauthTokenSecret:  

ReplayTable:
  all:
    - 
      - ["おはよう", !ruby/regexp /^(お|起)きた/, "むくり", "起床", "ムクリ", "ﾑｸﾘ", "おはよ", "okita", "お早う", "御早う"]
      - ["おはようなのだ！", "やっと起きたのかなのだ", "早くしないと、遅刻するのだ"]
    - 
      - ["だいごろう", "大五郎", "だいごろー", "daigorou"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["落ち込んでる", "欝だ", "低まる", "絶望した"]
      - ["どうしたのだ？", "元気を出すのだ！", "大丈夫かなのだ？"]
    - 
      - ["こんにちは", "こんにちわ", "hello", "はろー"]
      - ["こんにちわなのだ", "わんわん！", "はろーー", "(/ω・＼)ﾁﾗｯ"]
    - 
      - ["おやすみ","ねるか", "寝る", "ｵﾔｽﾐ"]
      - ["おやすみなのだ！", "さっさと寝るのだw", "おやすみ、また明日なのだ！", "また明日なのだ！"]
    - 
      - ["こんばんわ", "こんばんは"]
      - ["こんばんわなのだ！", "こんばんはなのだ！！"]
    - 
      - ["出発", "でっぱつ", "いってきます"]
      - ["いってらなのだ!"]
    - 
      - ["帰宅", "ただいま", "帰った"]
      - ["おかえりなのだ！", "おつかれなのだ！", "おかえりなのだ。"]
    - 
      - ["人生、宇宙、すべての答え", "The answer to life the universe and everything"]
      - ["42"]
    - 
      - ["バイトだん", "バイトから帰宅", "退社"]
      - ["お仕事お疲れなのだ！", "お疲れ様なのだ！", "バイト乙なのだ！", "おつかれなのだ！"]
#    - 
#      - ["あけおめ", "あけましておめでとう", "ことよろ", "今年もよろしく", "ことしもよろしく"]
#      - ["あけましておめでとうなのだ！ことしもよろしくなのだ（Ｕ＾ω＾）！"]
#    - 
#      - ["クリスマス"]
#      - ["メリー・クリスマスなのだ（Ｕ＾ω＾）", "シングルヘルでしょぉw（Ｕ＾ω＾）?", "プレゼントくれなのだ！", "ジングルベ〜ル♪"]
#   -
#      - ["ポッキー", "トッポ", "プリッツ"]
#      - ["僕も欲しいのだ（Ｕ＾ω＾）", "食べたいのだ（Ｕ＾ω＾）", "クレなのだ（Ｕ＾ω＾）"]
#    - 
#      - ["うける", "ウケる", "ウケル"]
#      - ["うけるーなのだ"]
#    - 
#      - ["死にたい"]
#      - ["僕は平成15年の夏に死んだのだ…。", "死んだら遺灰はのこるのか? なのだ"]
#    - 
#      - ["バレンタイン", "チョコ", "ちょこ", "バレンタイン"]
#      - ["僕もチョコが欲しいのだ！", "チョコ食べたいのだ！", "チョコ貰えるといいね！なのだ！"]
#    - 
#      - ["寒い", "さむい"]
#      - ["つくばの冬は僕の故郷のアラスカ並に寒いのだ…", "僕の冬毛をもってしても、つくばは寒いのだ…"]
#    - 
#      - ["バイト"]
#      - ["お疲れなのだ！", "バイト乙なのだ！", "おつかれーなのだ！"]

  mention:
    - 
      - ["ありがと", "おかあり", "おやあり", "てらあり"]
      - ["どういたしましてーなのだ！", "どーもなのだ。", "どういたしましてなのだ。"]
    - 
      - ["もふ", "もっふ"]
      - ["そんなに僕の毛皮でもふもふしたい？なのだ！", "僕の毛皮はもふもふなのだ！", "触ってみる？なのだ！"]
    - 
      - ["もしもし"]
      - ["呼ばれたかなのだ？", "僕のことを呼んだかなのだ？", "｜ω･`）チラッ", "｜･ω･`） ソー…", "（Ｕ>ω<)<ﾋﾟｸｯ"]
    - 
      - ["わんわん"]
      - ["（Ｕ＾ω＾）<わんわんお！", "わんわんわん！！", "<わんわん!!"]
    - 
      - ["だまれ", "うざい", "寝ない", "ねない", "違う", "ちがう"]
      - ["ごめんなのだ…", "(；Uﾟωﾟ)<すまないのだ！"]
    - 
      - ["あ?"]
      - ["（#U^ω^）ﾋﾟｷﾋﾟｷ"]
    - 
      - ["お手", "おて"]
      - ["へ（＾ω＾U) お手なのだ"]
    - 
      - ["おかわり"]
      - ["へ（＾ω＾U) おかわりなのだ"]
    - 
      - ["お座り", "おすわり"]
      - ["お座るのだ"]
    - 
      - ["∫"]
      - ["（Ｕ＾ω＾）つ http://www.wolframalpha.com/"]
    - 
      - ["ping", "ぴんぐ"]
      - ["pongなのだ", "pong"]
#    - 
#      - ["おみくじ"]
#      - 
#        - "【総合】大吉…ハッピーな1年になりそうなのだ（Ｕ＾ω＾）！"
#        - "【総合】中吉…何かいいことありそうなのだ！"
#        - "【総合】吉…良い１年になるといいねーなのだ！"
#        - "【総合】凶…試練の多い1年になりそうなのだ…がんばろーなのだ（Ｕ＾ω＾）！"
#        - "【総合】大凶…アンハッピーな1年になりそうなのだ…めげずにがんばろーなのだ！ふぁいとおー！！"
#        - "【恋愛】大吉…リア充爆発しろーなのだ！"
#        - "【恋愛】中吉…想いが伝わるかも…なのだ！！"
#        - "【恋愛】吉…運命の人と出会えるかもなのだ（Ｕ＾ω＾）！"
#        - "【恋愛】凶…えっちなことばっかり考えてると蔑んだ目で見られちゃうかも…なのだ(´・ω・｀)"
#        - "【恋愛】大凶…心に深いキズが残らないようにがんばろーなのだ…"
#        - "【金運】大吉…リッチになれそうなのだ！とんＱ連れてってほしいのだ（Ｕ＾ω＾）！"
#        - "【金運】中吉…良い買い物ができそうなのだ！"
#        - "【金運】吉…臨時収入があるかもなのだ（Ｕ＾ω＾）！"
#        - "【金運】凶…無駄な出費が多そうなのだ！薄い本の買いすぎには要注意なのだ！！"
#        - "【金運】大凶…財布を落とすかもなのだ…。でも、大丈夫！ぼくがちゃんと拾っておくのだ（Ｕ＾ω＾）！(しめしめ"
#        - "【勉強】大吉…成績アップできそうなのだ！がんばれなのだ（Ｕ＾ω＾）！！"
#        - "【勉強】中吉…苦手な科目が克服できるかも…なのだ！"
#        - "【勉強】吉…努力すればきっと報われるのだ！"
#        - "【勉強】凶…遅刻に注意なのだ！二度寝は危ないのだああああ！！！！"
#        - "【勉強】大凶…Twitterに勤しんでも単位は来ないのだ！留年がやってくるよーなのだ（Ｕ＾ω＾）！"
#        - "【仕事】大吉…今年もハッピーな社畜ライフを遅れそうなのだ！やったね！"
#        - "【仕事】中吉…大きな仕事を任されそうなのだ！"
#        - "【仕事】吉…頑張りが認められそうなのだ！"
#        - "【仕事】凶…ミスしちゃいそうなのだ…めげずにがんばろーなのだ！"
#        - "【仕事】大凶…お　ま　え　は　ク　ビ　だ　！"
#        - "【友情】大吉…エアじゃない友達ができるかも！なのだ（Ｕ＾ω＾）！！"
#        - "【友情】中吉…イベントで楽しい思い出ができそうなのだ！"
#        - "【友情】吉…けんかしちゃってもすぐ仲直りできそうなのだ！"
#        - "【友情】凶…1人のごはんもきっとおいしーのだ（Ｕ＾ω＾）"
#        - "【友情】大凶…一緒にいてあげるよなのだ！ひとりぼっちはさみしいもんな（Ｕ＾ω＾）！！"
Sandbox:
  level: 4
  timeout: 0.1

Function:
  all:

  mention:
    - ['(\w+)\s([0-9]+)進数', '"#{$1} = #{$1.to_i.to_s($2.to_i)}(#{$2}進数)\n#{$1}(#{$2}進数) = #{$1.to_i($2.to_i)}"']
    - ['(\w+)を([0-9]+)進数に', '"#{$1} = #{$1.to_i.to_s($2.to_i)}(#{$2}進数)"']
    - ['(\w+)\(([0-9]+)\)', '"#{$1} = #{$1.to_i.to_s($2.to_i)}(#{$2}進数)"']
    - ['(\w+)は([0-9]+)進数で', '"#{$1}(#{$2}進数) = #{$1.to_i($2.to_i)}"']

Calculate:
  alias:
    "mod": "%"
    "余り": "%"
    "あまり": "%"
    "×": "*"
    "かける": "*"
    "掛ける": "*"
    "÷": "/"
    "わる": "/"
    "割る": "/"
    "＋": "+"
    "たす": "+"
    "足す": "+"
    "ー": "-"
    "ひく": "-"
    "引く": "-"
    "＆": "&"
    "｜": "|"
    "xor": "^"
    "and": "&&"
    "or": "||"
    "not": "!"
    "∑": "Σ"
    "√": "√"
  alias_regexp:
    "([0-9]+)!": '"factorial(#{$1})"'
    "([0-9]+)P([0-9]+)": '"permutation(#{$1},#{$2})"'
    "([0-9]+)C([0-9]+)": '"combination(#{$1},#{$2})"'
    "([0-9]+)H([0-9]+)": '"repeated_combination(#{$1},#{$2})"'
  env: >
    alias ln log10;
    def e;E;end;
    def pi;PI;end;

    def factorial(n)
      (1..n).inject(:*)
    end

    def permutation(n,r)
      (n>=r) ? factorial(n) / factorial(n-r) : 0
    end

    def combination(n,r)
      (n>=r) ? factorial(n) / (factorial(n-r) * factorial(r)) : nil
    end

    def repeated_combination(n,r)
      combination(n+r+1, r)
    end

WordsOnFaildRegularTweet: 
  - "（Ｕ＾ω＾）わんわんお！なのだ"
  - "はあ、眠いのだ（Ｕ-ω-）zzz"
  - "僕の毛皮はふかふかなのだ"
  - "僕はアラスカンマラミュートという犬種なのだ"
  - "僕はまだ3歳なのだ"
  - "大五郎botって既出だったのかーなのだ…"
WordsOnFaildReply:
  - "そーなのだ"
  - "今は眠いのだ"
  - "そうなのだ（Ｕ＾ω＾）"
  - "呼ばれたかなのだ？"
  - "僕のことを呼んだかなのだ？"
  - "｜ω･`）チラッ"
  - "｜･ω･`） ソー…"

MentionLimit:
  interval: 5
  count: 10
  release: 600

Users:
  follow:
    - 92410518
    - 324380957
    - 246793872
    - 117341077
    - 135175693
    - 123862630
    - 128909217
    - 50046492 
    - 206248292
    - 86049415 
    - 14919778 
    - 282303420
    - 60046536 
    - 94797531 
    - 319554874
    - 84843705 
    - 90394630 
    - 427475071
    - 281079401
  remove:
    - "yamatosi3134"
    - "ameburo1"
    - "MARS_ON_Spotify"
    - "ios_dev_news"
    - "PhilnRaleigh"
    - "virtualworks1"
    - "WorldWide1001"
    - "kayo_silva15"
    - "TiagoJanatico"
    - "rnt_vdr"
    - "EsparZa_ROck"
    - "andre_estiano"
    - "Reglerium"
    - "licosupremus"
    - "pillowjack"
    - 524070668
    - 148658011
    - 636758363
    - 466543819
    - 104463917
    - 112567411
    - 130489531
    - 63384236
    - 174625216
    - 134665690
    - 43600056
    - 407567823
    - 95514455
    - 584300648
    - 70008095
    - 267293562
    - 447239619
    - 153640673
    - 351085603
    - 104209251
    - 586084120
    - 99701620
    - 96100867
    - 258096169
    - 46378888
    - 206521031
    - 274176272
    - 52689846
    - 389020153
    - 292229728
    - 241892876
    - 90905825
    - 50118140
    - 261042114
    - 546139549
    - 17568408
    - 195747980
    - 16702542
    - 19201678
    - 23159493
    - 28673371
    - 183484937
    - 441829370
    - 136274193
    - 534424353
    - 178052990
    - 436914110
    - 345672376
    - 402222107
    - 230706790
    - 269594479
    - 377703206
    - 427971295
    - 239227114
    - 70678420
    - 458430414
    - 219626285
    - 123593856
    - 197927220
    - 353359436
    - 553676554
    - 539747316
    - 546570918
    - 550358099
    - 545661547
    - 197744640
    - 274604105
    - 550505187
    - 552147567
    - 562282687
    - 562383894
    - 273744921
    - 299858063
    - 555625620
    - 565738096
    - 560627591
    - 383351477
    - 170066361
    - 565662478
    - 240901688
    - 166246775
    - 175168567
    - 82154425
    - 554061387
    - 419068462
    - 493622241
    - 18506975
    - 416776813
    - 27479529
    - 149966693
    - 337849119
    - 346129791
    - 392542269
    - 58578131
    - 111698159
    - 487952801
    - 277403754
    - 389215942
    - 23994973
    - 344729723
    - 175252654
    - 20859431
    - 249096055
    - 6086902
    - 367053616
    - 431329863
    - 179169850
    - 129760291
    - 437204437
    - 261096371
    - 234695726
    - 276159407
  ignore:
    - "run_entry"
    - 855178968
    #- "gam00222"
